# Generated by Django 5.2.11 on 2026-02-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='Texto del ejercicio. Puede incluir HTML básico.', verbose_name='enunciado')),
                ('formula_solucion', models.CharField(help_text='Fórmula en ASCII normalizado: ~ & | -> <-> Ejemplo: p -> (q & ~r)', max_length=500, verbose_name='fórmula solución')),
                ('tipo', models.CharField(choices=[('tabla_verdad', 'Tabla de verdad'), ('formalizacion', 'Formalización')], max_length=20, verbose_name='tipo')),
                ('es_publico', models.BooleanField(default=False, help_text='Si está marcado, el ejercicio es visible a todos los docentes (banco común). Si no, es privado del docente creador.', verbose_name='banco común')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Posición dentro de la práctica (1, 2, 3…).', verbose_name='orden')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_practicas', to='ejercicios.ejercicio', verbose_name='ejercicio')),
            ],
            options={
                'verbose_name': 'ejercicio en práctica',
                'verbose_name_plural': 'ejercicios en prácticas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_raw', models.CharField(help_text='Fórmula enviada por el estudiante en ASCII normalizado.', max_length=500, verbose_name='respuesta')),
                ('es_correcto', models.BooleanField(verbose_name='es correcto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('ejercicio_practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='ejercicios.ejerciciopractica', verbose_name='ejercicio en práctica')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'intento',
                'verbose_name_plural': 'intentos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ejemplo: "Práctica 1 – Tablas de verdad".', max_length=200, verbose_name='título')),
                ('orden', models.PositiveIntegerField(help_text='Orden de la práctica dentro de la comisión (1, 2, 3…).', verbose_name='orden')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='cursos.comision', verbose_name='comisión')),
                ('ejercicios', models.ManyToManyField(blank=True, through='ejercicios.EjercicioPractica', to='ejercicios.ejercicio', verbose_name='ejercicios')),
            ],
            options={
                'verbose_name': 'práctica',
                'verbose_name_plural': 'prácticas',
                'ordering': ['orden'],
                'unique_together': {('comision', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='ejerciciopractica',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicio_practicas', to='ejercicios.practica', verbose_name='práctica'),
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciopractica',
            unique_together={('practica', 'orden')},
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_practica_actual', models.ForeignKey(blank=True, help_text='Null = práctica completada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progresos_actuales', to='ejercicios.ejerciciopractica', verbose_name='ejercicio actual')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='ejercicios.practica', verbose_name='práctica')),
            ],
            options={
                'verbose_name': 'progreso',
                'verbose_name_plural': 'progresos',
                'unique_together': {('estudiante', 'practica')},
            },
        ),
    ]
