# Generated by Django 5.2.11 on 2026-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intento",
            name="comentario_docente",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comentario opcional del docente/admin sobre este intento.",
                null=True,
                verbose_name="comentario docente",
            ),
        ),
    ]
