# Generated by Django 6.0.2 on 2026-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_intento_comentario_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='diccionario',
            field=models.JSONField(blank=True, default=dict, help_text='Mapa {letra: proposición} construido por el estudiante. Ej: {"A": "Llueve", "B": "Hay tráfico"}.', verbose_name='diccionario de variables'),
        ),
    ]
