# Generated by Django 6.0.2 on 2026-02-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_add_diccionario_to_intento'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='aprobado_docente',
            field=models.BooleanField(blank=True, default=None, help_text='None = pendiente de revisión, True = aprobado por docente, False = rechazado por docente.', null=True, verbose_name='aprobación docente'),
        ),
    ]
