# Generated by Django 6.0.2 on 2026-02-19 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_add_aprobado_docente_to_intento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AddField(
            model_name='practica',
            name='es_publica',
            field=models.BooleanField(default=False, help_text='Si está marcado, la práctica (con todos sus ejercicios) es visible a todos los docentes para ser importada a sus comisiones.', verbose_name='banco común'),
        ),
    ]
