# Generated by Django 6.0.2 on 2026-02-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0007_intento_tabla_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='diccionario_solucion',
            field=models.JSONField(blank=True, default=dict, help_text='Diccionario de variables usado por el docente al crear el ejercicio.', verbose_name='diccionario solución'),
        ),
    ]
