# Generated by Django 6.0.2 on 2026-02-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0008_diccionario_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, help_text='Opcional. Si se indica, los estudiantes no pueden acceder antes de esta fecha y hora.', null=True, verbose_name='apertura'),
        ),
        migrations.AddField(
            model_name='practica',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, help_text='Opcional. Si se indica, los estudiantes no pueden acceder después de esta fecha y hora.', null=True, verbose_name='cierre'),
        ),
    ]
