# Generated by Django 6.0.2 on 2026-02-21 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0009_practica_fecha_apertura_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['estudiante', 'ejercicio_practica'], name='intento_est_ep_idx'),
        ),
    ]
