# Generated by Django 6.0.2 on 2026-02-25 12:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0010_indice_intento_estudiante_ep'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción opcional de la práctica, visible para los estudiantes. Puede incluir formato (negritas, listas, etc.).', null=True, verbose_name='descripción'),
        ),
    ]
