# Generated by Django 6.0.2 on 2026-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0011_practica_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='formula_solucion',
            field=models.CharField(help_text='Fórmula en ASCII normalizado: ~ . & | -> <-> Ejemplo: p -> (q . ~r)', max_length=500, verbose_name='fórmula solución'),
        ),
    ]
