# Generated by Django 6.0.2 on 2026-03-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0012_alter_ejercicio_formula_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='practica_origen',
            field=models.ForeignKey(blank=True, help_text='Si esta práctica fue importada desde otra, apunta al original. Se limpia automáticamente cuando la práctica es modificada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='ejercicios.practica', verbose_name='importada desde'),
        ),
    ]
