# Generated by Django 6.0.2 on 2026-03-08 23:03

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


# ---------------------------------------------------------------------------
# Funciones de migración de datos
# ---------------------------------------------------------------------------

def crear_practicacomisiones(apps, schema_editor):
    """Crea un PracticaComision por cada Practica existente, copiando comision,
    orden, fecha_apertura y fecha_cierre desde la Practica original."""
    Practica = apps.get_model('ejercicios', 'Practica')
    PracticaComision = apps.get_model('ejercicios', 'PracticaComision')
    for p in Practica.objects.select_related('comision').all():
        PracticaComision.objects.create(
            practica=p,
            comision=p.comision,
            orden=p.orden,
            fecha_apertura=p.fecha_apertura,
            fecha_cierre=p.fecha_cierre,
        )


def deduplicar_practicas(apps, schema_editor):
    """Identifica prácticas idénticas (mismo título + mismos ejercicios en el
    mismo orden) y las fusiona, conservando la de pk más bajo como canónica.

    Para cada grupo de duplicados:
    - Redirige PracticaComision del duplicado al canónico.
    - Redirige Intentos hacia el EjercicioPractica correspondiente del canónico.
    - Redirige practica_origen de otras prácticas al canónico.
    - Elimina los EjercicioPractica y la Practica duplicada.
    """
    Practica = apps.get_model('ejercicios', 'Practica')
    PracticaComision = apps.get_model('ejercicios', 'PracticaComision')
    EjercicioPractica = apps.get_model('ejercicios', 'EjercicioPractica')
    Intento = apps.get_model('ejercicios', 'Intento')

    grupos = defaultdict(list)
    for p in Practica.objects.prefetch_related('ejercicio_practicas').all():
        eps = tuple(
            p.ejercicio_practicas.order_by('orden').values_list('ejercicio_id', 'orden')
        )
        fp = (p.titulo, eps)
        grupos[fp].append(p)

    for fp, practicas in grupos.items():
        if len(practicas) == 1:
            continue

        # El de pk más bajo es el canónico
        practicas.sort(key=lambda p: p.pk)
        canonical = practicas[0]

        for dup in practicas[1:]:
            # Redirigir PracticaComision al canónico
            PracticaComision.objects.filter(practica=dup).update(practica=canonical)

            # Redirigir Intentos: sus EjercicioPractica apuntan al dup,
            # deben apuntar al EP correspondiente del canónico.
            for ep_dup in EjercicioPractica.objects.filter(practica=dup):
                try:
                    ep_canonical = EjercicioPractica.objects.get(
                        practica=canonical,
                        ejercicio_id=ep_dup.ejercicio_id,
                        orden=ep_dup.orden,
                    )
                except EjercicioPractica.DoesNotExist:
                    # No debería ocurrir si el fingerprint es correcto,
                    # pero en caso de inconsistencia conservamos el ep_dup
                    # movido al canónico.
                    ep_dup.practica = canonical
                    ep_dup.save(update_fields=['practica'])
                    continue
                Intento.objects.filter(ejercicio_practica=ep_dup).update(
                    ejercicio_practica=ep_canonical
                )

            # Redirigir practica_origen de otras prácticas al canónico
            Practica.objects.filter(practica_origen=dup).update(practica_origen=canonical)

            # Limpiar EPs del duplicado y la práctica misma
            EjercicioPractica.objects.filter(practica=dup).delete()
            dup.delete()


def rellenar_practica_comision_en_intentos(apps, schema_editor):
    """Asigna Intento.practica_comision basándose en la práctica a la que
    apunta su EjercicioPractica.  Usa bulk_update en chunks de 500."""
    Intento = apps.get_model('ejercicios', 'Intento')
    PracticaComision = apps.get_model('ejercicios', 'PracticaComision')

    # Construimos un mapa practica_id → PracticaComision para evitar N queries
    pc_por_practica = {
        pc.practica_id: pc
        for pc in PracticaComision.objects.all()
    }

    intentos = list(
        Intento.objects.select_related('ejercicio_practica__practica').all()
    )

    chunk_size = 500
    for i in range(0, len(intentos), chunk_size):
        chunk = intentos[i : i + chunk_size]
        for intento in chunk:
            practica_id = intento.ejercicio_practica.practica_id
            intento.practica_comision = pc_por_practica.get(practica_id)
        Intento.objects.bulk_update(chunk, ['practica_comision'])


def noop(apps, schema_editor):
    pass


# ---------------------------------------------------------------------------
# Migración
# ---------------------------------------------------------------------------

class Migration(migrations.Migration):

    # PostgreSQL no permite mezclar DDL y DML en la misma transacción cuando
    # hay FK con deferred triggers pendientes. RunPython crea PracticaComision
    # (FK a ejercicios_practica) y luego RemoveField intenta ALTER TABLE
    # ejercicios_practica en la misma txn → "pending trigger events".
    # Con atomic=False cada operación se confirma de forma independiente.
    atomic = False

    dependencies = [
        ('cursos', '0001_initial'),
        ('ejercicios', '0014_indices_rendimiento'),
    ]

    operations = [
        # ── Estructura previa a los datos ──────────────────────────────────
        migrations.AlterModelOptions(
            name='practica',
            options={'ordering': ['titulo'], 'verbose_name': 'práctica', 'verbose_name_plural': 'prácticas'},
        ),
        migrations.AlterUniqueTogether(
            name='practica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='practica',
            name='practica_origen',
            field=models.ForeignKey(blank=True, help_text='Si esta práctica fue importada desde otra, apunta al original. Se limpia automáticamente cuando la práctica es modificada (copy-on-write).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='ejercicios.practica', verbose_name='importada desde'),
        ),
        migrations.CreateModel(
            name='PracticaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden de la práctica dentro de la comisión (1, 2, 3…).', verbose_name='orden')),
                ('fecha_apertura', models.DateTimeField(blank=True, help_text='Opcional. Si se indica, los estudiantes no pueden acceder antes de esta fecha y hora.', null=True, verbose_name='apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Opcional. Si se indica, los estudiantes no pueden acceder después de esta fecha y hora.', null=True, verbose_name='cierre')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_comisiones', to='cursos.comision', verbose_name='comisión')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_comisiones', to='ejercicios.practica', verbose_name='práctica')),
            ],
            options={
                'verbose_name': 'práctica en comisión',
                'verbose_name_plural': 'prácticas en comisiones',
                'ordering': ['orden'],
                'unique_together': {('comision', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='intento',
            name='practica_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='ejercicios.practicacomision', verbose_name='práctica en comisión'),
        ),

        # ── Migración de datos ─────────────────────────────────────────────
        migrations.RunPython(crear_practicacomisiones, reverse_code=noop),
        migrations.RunPython(deduplicar_practicas,     reverse_code=noop),
        migrations.RunPython(rellenar_practica_comision_en_intentos, reverse_code=noop),

        # ── Estructura post-datos ──────────────────────────────────────────
        migrations.RemoveField(
            model_name='practica',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='orden',
        ),
    ]
