# Generated by Django 5.2.13 on 2026-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0016_merge_error_categoria_practicacomision"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="valores_verdad_solucion",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Solo para ejercicios de determinación de verdad. Mapa {letra: bool} con el valor de verdad asignado a cada variable. Ej: {"A": true, "B": false}.',
                null=True,
                verbose_name="valores de verdad solución",
            ),
        ),
        migrations.AddField(
            model_name="intento",
            name="valor_verdad_estudiante",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Solo para ejercicios de determinación de verdad. Valor de verdad que el estudiante declaró para su fórmula (V o F).",
                null=True,
                verbose_name="valor de verdad asignado",
            ),
        ),
        migrations.AddField(
            model_name="intento",
            name="valores_verdad",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Solo para ejercicios de determinación de verdad. Mapa {letra: bool} con el valor de verdad asignado por el estudiante a cada variable. Ej: {"A": true, "B": false}.',
                null=True,
                verbose_name="valores de verdad del diccionario",
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("tabla_verdad", "Tabla de verdad"),
                    ("formalizacion", "Formalización"),
                    ("determinacion_verdad", "Determinación de valor de verdad"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
    ]
