# Generated by Django 5.2.13 on 2026-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0017_add_determinacion_verdad_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="intento",
            name="juicio_estudiante",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Solo para ejercicios de tabla de verdad. True = el estudiante declaró el argumento como válido, False = inválido, None = no indicado.",
                null=True,
                verbose_name="juicio de validez del estudiante",
            ),
        ),
    ]
