# Generated by Django 6.0.2 on 2026-08-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0022_practicacomision_desbloqueo_secuencial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progreso',
            name='practica_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='ejercicios.practicacomision', verbose_name='práctica en comisión'),
        ),
    ]
