# Generated by Django 6.0.2 on 2026-08-08 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0024_backfill_progreso_por_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('estudiante', 'practica_comision')},
        ),
        migrations.AlterField(
            model_name='progreso',
            name='practica_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='ejercicios.practicacomision', verbose_name='práctica en comisión'),
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='practica',
        ),
    ]
