# Generated by Django 6.0.2 on 2026-08-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0025_progreso_clave_por_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intento',
            name='practica_comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='ejercicios.practicacomision', verbose_name='práctica en comisión'),
        ),
    ]
