# Generated by Django 6.0.2 on 2026-08-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_inscripcion_cohorte_parcial_cohorte'),
        ('ejercicios', '0026_intento_practica_comision_obligatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='cursos.cohorte', verbose_name='cohorte'),
        ),
    ]
