# Generated by Django 6.0.2 on 2026-08-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_cohorte_not_null'),
        ('ejercicios', '0027_intento_cohorte_progreso_cohorte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='intento',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('estudiante', 'practica_comision', 'cohorte')},
        ),
    ]
