# Generated by Django 6.0.5 on 2026-08-28 01:34

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0029_traducciones_contenido_pedagogico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='enunciado_zh_hans',
            field=models.TextField(blank=True, default='', help_text='Traducción opcional. Si queda vacía se mostrará el castellano original.', verbose_name='enunciado en chino simplificado'),
        ),
        migrations.AddField(
            model_name='practica',
            name='descripcion_zh_hans',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='descripción en chino simplificado'),
        ),
        migrations.AddField(
            model_name='practica',
            name='titulo_zh_hans',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='título en chino simplificado'),
        ),
    ]
