# Generated by Django 5.2.11 on 2026-02-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: "IPC – Turno Noche 2025".', max_length=100, verbose_name='nombre')),
                ('docentes', models.ManyToManyField(blank=True, limit_choices_to={'es_docente': True}, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='docentes')),
            ],
            options={
                'verbose_name': 'comisión',
                'verbose_name_plural': 'comisiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripción')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.comision', verbose_name='comisión')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['comision', 'estudiante'],
                'unique_together': {('estudiante', 'comision')},
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'es_docente': False, 'is_staff': False}, related_name='comisiones_inscripto', through='cursos.Inscripcion', to=settings.AUTH_USER_MODEL, verbose_name='estudiantes'),
        ),
    ]
