# Generated by Django 6.0.2 on 2026-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='tipo_encuesta',
            field=models.CharField(choices=[('completa', 'Completa (datos básicos + 3 consentimientos + encuesta socioeducativa)'), ('basica', 'Básica (datos básicos + consentimiento pedagógico)')], default='completa', help_text='Determina si el onboarding incluye la encuesta socioeducativa completa o solo los datos básicos y el consentimiento pedagógico.', max_length=10, verbose_name='tipo de encuesta de onboarding'),
        ),
    ]
