# Generated by Django 6.0.2 on 2026-05-24 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_encuesta_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Parcial 1", "Recuperatorio".', max_length=100, verbose_name='nombre')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('puntaje_total', models.DecimalField(decimal_places=2, help_text='Máximo posible de la parte de lógica.', max_digits=5, verbose_name='puntaje total (parte lógica)')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parciales', to='cursos.comision', verbose_name='comisión')),
            ],
            options={
                'verbose_name': 'parcial',
                'verbose_name_plural': 'parciales',
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NotaParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='puntaje')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_parciales', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('parcial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='cursos.parcial', verbose_name='parcial')),
            ],
            options={
                'verbose_name': 'nota de parcial',
                'verbose_name_plural': 'notas de parcial',
                'ordering': ['estudiante__last_name', 'estudiante__first_name', 'estudiante__username'],
                'unique_together': {('parcial', 'estudiante')},
            },
        ),
    ]
