# Generated by Django 6.0.2 on 2026-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_parcial_notaparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaparcial',
            name='ausente',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante no se presentó. Cuando es True, puntaje y puntaje_logica deben ser null.', verbose_name='ausente al parcial'),
        ),
        migrations.AddField(
            model_name='notaparcial',
            name='puntaje_logica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje de la sección de lógica del parcial (subconjunto del puntaje global).', max_digits=5, null=True, verbose_name='puntaje parte lógica'),
        ),
        migrations.AddField(
            model_name='parcial',
            name='umbral_aprobacion',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Nota mínima normalizada (0-10) para aprobar. Default 4.00, igual que la serie histórica.', max_digits=4, verbose_name='umbral aprobación (sobre 10)'),
        ),
        migrations.AddField(
            model_name='parcial',
            name='umbral_promocion',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Nota mínima normalizada (0-10) para promocionar. Default 7.00, igual que la serie histórica.', max_digits=4, verbose_name='umbral promoción (sobre 10)'),
        ),
    ]
