# Generated by Django 6.0.2 on 2026-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_puntaje_logica_nota_logica_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaparcial',
            name='ausente',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante no se presentó. Cuando es True, puntaje y nota_logica_parcial deben ser null.', verbose_name='ausente al parcial'),
        ),
        migrations.AlterField(
            model_name='notaparcial',
            name='nota_logica_parcial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje de la sección de lógica del parcial (subconjunto del puntaje global).', max_digits=5, null=True, verbose_name='nota sección lógica'),
        ),
    ]
