# Generated by Django 6.0.2 on 2026-08-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_sincronizar_metadatos_notaparcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º')], verbose_name='cuatrimestre')),
                ('activa', models.BooleanField(default=False, help_text='El cuatrimestre en curso. Solo puede haber una activa.', verbose_name='cohorte activa')),
            ],
            options={
                'verbose_name': 'cohorte',
                'verbose_name_plural': 'cohortes',
                'ordering': ['-anio', '-cuatrimestre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('activa',), name='unica_cohorte_activa')],
                'unique_together': {('anio', 'cuatrimestre')},
            },
        ),
    ]
