# Generated by Django 6.0.2 on 2026-08-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_cohorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AddField(
            model_name='parcial',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parciales', to='cursos.cohorte', verbose_name='cohorte'),
        ),
    ]
