# Generated by Django 6.0.2 on 2026-08-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_backfill_cohorte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AlterField(
            model_name='parcial',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parciales', to='cursos.cohorte', verbose_name='cohorte'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'comision', 'cohorte')},
        ),
    ]
