# Generated by Django 6.0.2 on 2026-02-20 20:16

from django.db import migrations, models


def activar_para_nunca_logueados(apps, schema_editor):
    """Marca debe_cambiar_password=True para usuarios que nunca iniciaron sesión."""
    Usuario = apps.get_model('accounts', 'Usuario')
    Usuario.objects.filter(last_login__isnull=True, is_staff=False).update(debe_cambiar_password=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si True, el usuario será redirigido a cambiar su contraseña en el próximo login. Se activa al crear la cuenta y se limpia cuando el usuario guarda una nueva contraseña.', verbose_name='debe cambiar contraseña'),
        ),
        migrations.RunPython(activar_para_nunca_logueados, migrations.RunPython.noop),
    ]
