# Generated by Django 6.0.2 on 2026-02-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_debe_cambiar_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='IPC · Lógica', max_length=100, verbose_name='nombre del sitio')),
                ('color_primario', models.CharField(default='#1a1a2e', help_text='Color de la barra de navegación y botones principales (hex, ej: #1a1a2e).', max_length=7, verbose_name='color primario')),
                ('color_acento', models.CharField(default='#2e6da4', help_text='Color de la barra de rol docente y links en la nav (hex, ej: #2e6da4).', max_length=7, verbose_name='color de acento')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
    ]
