# Generated by Django 6.0.2 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configsitio_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsitio',
            name='error_consenso_min',
            field=models.PositiveSmallIntegerField(default=2, help_text='Mínimo de estudiantes distintos que deben compartir la misma respuesta incorrecta para que aparezca en el panel "Errores compartidos". Valor recomendado: 2.', verbose_name='umbral de errores compartidos'),
        ),
    ]
