# Generated by Django 5.2.12 on 2026-03-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_configsitio_umbrales_analiticos"),
        ("accounts", "0007_encuesta_onboarding"),
    ]

    operations = []
