# Generated by Django 5.2.12 on 2026-03-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20260310_0732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="provincia_origen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buenos_aires", "Buenos Aires (Interior)"),
                    ("caba", "Ciudad Autónoma de Buenos Aires"),
                    ("catamarca", "Catamarca"),
                    ("chaco", "Chaco"),
                    ("chubut", "Chubut"),
                    ("cordoba", "Córdoba"),
                    ("corrientes", "Corrientes"),
                    ("entre_rios", "Entre Ríos"),
                    ("formosa", "Formosa"),
                    ("jujuy", "Jujuy"),
                    ("la_pampa", "La Pampa"),
                    ("la_rioja", "La Rioja"),
                    ("mendoza", "Mendoza"),
                    ("misiones", "Misiones"),
                    ("neuquen", "Neuquén"),
                    ("rio_negro", "Río Negro"),
                    ("salta", "Salta"),
                    ("san_juan", "San Juan"),
                    ("san_luis", "San Luis"),
                    ("santa_cruz", "Santa Cruz"),
                    ("santa_fe", "Santa Fe"),
                    ("santiago_del_estero", "Santiago del Estero"),
                    ("tierra_del_fuego", "Tierra del Fuego"),
                    ("tucuman", "Tucumán"),
                ],
                default="",
                max_length=30,
                verbose_name="provincia de origen",
            ),
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="tipo_escuela",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bachillerato", "Bachillerato"),
                    ("comercial", "Comercial"),
                    ("tecnico", "Técnico Profesional"),
                    ("artistica", "Artística"),
                    ("especial", "Especial"),
                    ("rural", "Rural"),
                    ("ja", "de Jóvenes y Adultos"),
                    ("intercultural", "Intercultural Bilingüe"),
                    ("domiciliaria", "Domiciliaria/Hospitalaria"),
                    ("encierro", "en Contexto de Encierro"),
                ],
                default="",
                max_length=20,
                verbose_name="tipo de escuela secundaria",
            ),
        ),
    ]
