# Generated by Django 5.2.12 on 2026-03-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_encuestaestudiante_provincia_origen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuestaestudiante",
            name="acertijo_cirugia_no_se",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="acertijo cirugía: no sabe"
            ),
        ),
        migrations.AddField(
            model_name="encuestaestudiante",
            name="email_tipo",
            field=models.CharField(
                blank=True,
                choices=[("no_tengo", "No tengo"), ("otras", "Otras")],
                default="",
                max_length=10,
                verbose_name="disponibilidad de correo electrónico",
            ),
        ),
        migrations.AddField(
            model_name="encuestaestudiante",
            name="motivo_no_termino_ipc_otras",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="motivo no terminó IPC (otras)",
            ),
        ),
        migrations.AddField(
            model_name="encuestaestudiante",
            name="tipo_inst_fuera_uba_otras",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="institución fuera de UBA (otras)",
            ),
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="motivo_no_termino_ipc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "Dejé la materia por motivos personales"),
                    ("laboral", "Dejé la materia por motivos laborales"),
                    ("priorice", "Priorizé la aprobación de otras materias"),
                    ("ausencias", "Perdí la regularidad por ausencias"),
                    (
                        "promedio",
                        "No alcancé el promedio necesario para rendir el examen final",
                    ),
                    ("final", "No logré aprobar el examen final"),
                    ("vencio", "Se me venció la materia"),
                    ("otra", "Otras"),
                ],
                default="",
                max_length=20,
                verbose_name="motivo por el que no terminó IPC",
            ),
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="tipo_inst_fuera_uba",
            field=models.CharField(
                blank=True,
                choices=[
                    ("universidad", "Universidad"),
                    ("formacion_tecnica", "Instituto de Formación Técnica Superior"),
                    ("profesorado", "Profesorado"),
                    ("otras", "Otras"),
                ],
                default="",
                max_length=20,
                verbose_name="tipo de institución (fuera de UBA)",
            ),
        ),
    ]
