# Generated by Django 5.2.12 on 2026-03-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_encuestaestudiante_acertijo_cirugia_no_se_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encuestaestudiante",
            name="email_tipo",
        ),
    ]
