# Generated by Django 5.2.12 on 2026-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_encuestaestudiante_email_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="situacion_laboral",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_trabajo", "No trabajo y no estoy buscando"),
                    ("busco", "Busco trabajo"),
                    ("hasta_4", "Trabajo hasta 4 horas por d\u00eda"),
                    ("4_6", "Trabajo entre 4 y 6 horas por d\u00eda"),
                    ("mas_6", "Trabajo 6 o m\u00e1s horas por d\u00eda"),
                ],
                default="",
                max_length=15,
                verbose_name="situaci\u00f3n laboral",
            ),
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="dias_trabaja",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "No trabajo"),
                    ("menos_5", "Trabajo menos de 5 d\u00edas a la semana"),
                    ("5", "Trabajo 5 d\u00edas de la semana"),
                    ("mas_5", "Trabajo m\u00e1s de 5 d\u00edas a la semana"),
                ],
                default="",
                max_length=10,
                verbose_name="d\u00edas que trabaja",
            ),
        ),
    ]
