# Generated by Django 5.2.12 on 2026-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_encuestaestudiante_situacion_laboral_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="tiempo_desde_secundaria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menos_1", "Menos de un a\u00f1o"),
                    ("1_3", "Entre 1 y 3 a\u00f1os"),
                    ("mas_3", "M\u00e1s de 3 a\u00f1os"),
                ],
                default="",
                max_length=15,
                verbose_name="tiempo desde secundaria",
            ),
        ),
    ]
