# Generated by Django 5.2.12 on 2026-03-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_encuestaestudiante_tiempo_desde_secundaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="acertijo_silogismo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mas_alto", "M\u00e1s alto"),
                    ("mas_bajo", "M\u00e1s bajo"),
                ],
                default="",
                max_length=10,
                verbose_name="acertijo: silogismo",
            ),
        ),
    ]
