# Generated by Django 5.2.12 on 2026-03-11 02:32

from django.db import migrations, models


def migrar_acertijo_cirugia(apps, schema_editor):
    EncuestaEstudiante = apps.get_model("accounts", "EncuestaEstudiante")
    for encuesta in EncuestaEstudiante.objects.all().only("id", "acertijo_cirugia_no_se", "acertijo_cirugia"):
        if encuesta.acertijo_cirugia_no_se:
            encuesta.acertijo_cirugia = "No s\u00e9"
            encuesta.save(update_fields=["acertijo_cirugia"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_encuestaestudiante_acertijo_silogismo"),
    ]

    operations = [
        migrations.RunPython(migrar_acertijo_cirugia, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="encuestaestudiante",
            name="acertijo_cirugia_no_se",
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="acertijo_cirugia",
            field=models.TextField(blank=True, default="", verbose_name="acertijo: cirug\u00eda"),
        ),
    ]
