# Generated by Django 5.2.12 on 2026-03-11 02:50

from django.db import migrations, models


TIPO_INST_LABELS = {
    "universidad": "Universidad",
    "formacion_tecnica": "Instituto de Formaci\u00f3n T\u00e9cnica Superior",
    "profesorado": "Profesorado",
    "otras": "Otras",
}

MOTIVO_LABELS = {
    "personal": "Dej\u00e9 la materia por motivos personales",
    "laboral": "Dej\u00e9 la materia por motivos laborales",
    "priorice": "Prioriz\u00e9 la aprobaci\u00f3n de otras materias",
    "ausencias": "Perd\u00ed la regularidad por ausencias",
    "promedio": "No alcanc\u00e9 el promedio necesario para rendir el examen final",
    "final": "No logr\u00e9 aprobar el examen final",
    "vencio": "Se me venci\u00f3 la materia",
    "otra": "Otras",
}


def migrar_respuestas_unificadas(apps, schema_editor):
    EncuestaEstudiante = apps.get_model("accounts", "EncuestaEstudiante")
    for encuesta in EncuestaEstudiante.objects.all().only(
        "id",
        "tipo_inst_fuera_uba",
        "tipo_inst_fuera_uba_otras",
        "motivo_no_termino_ipc",
        "motivo_no_termino_ipc_otras",
    ):
        updates = []

        if encuesta.tipo_inst_fuera_uba == "otras":
            encuesta.tipo_inst_fuera_uba = encuesta.tipo_inst_fuera_uba_otras or ""
            updates.append("tipo_inst_fuera_uba")
        elif encuesta.tipo_inst_fuera_uba:
            encuesta.tipo_inst_fuera_uba = TIPO_INST_LABELS.get(encuesta.tipo_inst_fuera_uba, encuesta.tipo_inst_fuera_uba)
            updates.append("tipo_inst_fuera_uba")

        if encuesta.motivo_no_termino_ipc == "otra":
            encuesta.motivo_no_termino_ipc = encuesta.motivo_no_termino_ipc_otras or ""
            updates.append("motivo_no_termino_ipc")
        elif encuesta.motivo_no_termino_ipc:
            encuesta.motivo_no_termino_ipc = MOTIVO_LABELS.get(encuesta.motivo_no_termino_ipc, encuesta.motivo_no_termino_ipc)
            updates.append("motivo_no_termino_ipc")

        if updates:
            encuesta.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_colapsar_acertijo_cirugia_en_un_campo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="tipo_inst_fuera_uba",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="tipo de instituci\u00f3n (fuera de UBA)"),
        ),
        migrations.AlterField(
            model_name="encuestaestudiante",
            name="motivo_no_termino_ipc",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="motivo por el que no termin\u00f3 IPC"),
        ),
        migrations.RunPython(migrar_respuestas_unificadas, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="encuestaestudiante",
            name="tipo_inst_fuera_uba_otras",
        ),
        migrations.RemoveField(
            model_name="encuestaestudiante",
            name="motivo_no_termino_ipc_otras",
        ),
    ]
