# Generated by Django 6.0.5 on 2026-08-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_configsitio_contacto_privacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsitio',
            name='idioma_predeterminado',
            field=models.CharField(choices=[('es', 'Castellano'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('zh-hans', '简体中文')], default='es', help_text='Idioma que verá quien todavía no haya elegido uno. Cada persona puede cambiarlo luego desde el selector del sitio.', max_length=7, verbose_name='idioma predeterminado'),
        ),
    ]
